### ISSUE TITLE
Python版本無法收斂問題

### ISSUE THREAD

**Issue by CatDuke** [whuang022ai/AI-Tutorial-Multilayer-Perceptron#4]
![image](https://user-images.githubusercontent.com/26783645/42077250-d44e3358-7baa-11e8-8d92-9a8340c764b0.png)

請問大大，我在測試code的時候，請教一下：
關於程式碼：form datetime import datetime
這部分使用用途? 不知道如何使用，因有錯誤提示產生，先行註解
執行程式結果無法達成收斂效果，請問如何解決 ?

**Comment by CatDuke** [comment]
![image](https://user-images.githubusercontent.com/26783645/42078158-06c170fe-7bae-11e8-983d-72284010a8ea.png)

公式錯誤，改成+b1，就可以成功收斂。

**Comment by whuang022ai** [comment]
感謝Bug提供，已經修正

**Comment by whuang022ai** [comment]
感謝Bug提供，已經修正
